### ISSUE TITLE
Add .nvmrc file

### ISSUE THREAD

**Issue by kee-oth** [PatrickDev14/portfolio-v3#9]
Let's add an `.nvmrc` file that specifies node v18.15.0.

This will document the node version for ourselves and anyone else that wants to run the project. Plus, if they're using compatible tooling (like nvm or asdf), they can easily switch to it.

To switch to the `.nvmrc` file's specific node version when using nvm, run:
`nvm use`

**Comment by PatrickDev14** [comment]
`.nvmrc` is added for node v18.16.0 to the `development` branch.
